// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDm3iuFToa08xlWdRZUxwtUuM5iKrV-y6I',
    appId: '1:1056386289923:web:90d7d511ebae2ae61c9936',
    messagingSenderId: '1056386289923',
    projectId: 'blood-donation-44cd3',
    authDomain: 'blood-donation-44cd3.firebaseapp.com',
    storageBucket: 'blood-donation-44cd3.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARsOuSRa6KambimZNMi9lkQyJRVXLw6CA',
    appId: '1:1056386289923:android:3bd50e3bc7ecb7eb1c9936',
    messagingSenderId: '1056386289923',
    projectId: 'blood-donation-44cd3',
    storageBucket: 'blood-donation-44cd3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2PgJOTTgESycipoEVjehB0WXq4jNkygA',
    appId: '1:1056386289923:ios:f148fdae7f2d31f61c9936',
    messagingSenderId: '1056386289923',
    projectId: 'blood-donation-44cd3',
    storageBucket: 'blood-donation-44cd3.appspot.com',
    iosBundleId: 'com.example.bloodDonation',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB2PgJOTTgESycipoEVjehB0WXq4jNkygA',
    appId: '1:1056386289923:ios:d88cfe8c9b44eda11c9936',
    messagingSenderId: '1056386289923',
    projectId: 'blood-donation-44cd3',
    storageBucket: 'blood-donation-44cd3.appspot.com',
    iosBundleId: 'com.example.bloodDonation.RunnerTests',
  );
}
